version: 0.2

phases:
  install: # Dynamically generate helm values file
    commands:
      - "API_IMAGE_TAG=$(source ./tags.txt && echo ${Api_Image_Tag})"
      - "DDB_IMAGE_TAG=$(source ./tags.txt && echo ${Dynamo_Image_Tag})"
      - "WEBAPP_IMAGE_TAG=$(source ./tags.txt && echo ${Webapp_Image_Tag})"
      - "NODEJS_IMAGE_TAG=$(source ./tags.txt && echo ${Nodejs_Image_Tag})"
      - "PYTHON_IMAGE_TAG=$(source ./tags.txt && echo ${Python_Image_Tag})"
      
  build: # Generate values file
    commands:
      - git clone ${GITHUB_HELM_REPO_URL}
      - |
        cat <<EOF > ${CODEBUILD_SRC_DIR}/${GITHUB_HELM_REPO_NAME}/${HELM_CHART_NAME}/${VALUES_FILE_NAME}
        api_image_tag: ${API_IMAGE_TAG}
        dynamo_image_tag: ${DDB_IMAGE_TAG}
        webapp_image_tag: ${WEBAPP_IMAGE_TAG}
        nodejs_image_tag: ${NODEJS_IMAGE_TAG}
        python_image_tag: ${PYTHON_IMAGE_TAG}
        EOF
      - cat ${CODEBUILD_SRC_DIR}/${GITHUB_HELM_REPO_NAME}/${HELM_CHART_NAME}/${VALUES_FILE_NAME}
      
  post_build: # Push the Docker image to the ECR
    commands:
      - git config user.email ${GITHUB_OWNER_EMAIL}
      - cd ${CODEBUILD_SRC_DIR}/${GITHUB_HELM_REPO_NAME}/${HELM_CHART_NAME}/ &&  git add ${VALUES_FILE_NAME} && git commit -m "Updated values file"
      - git push https://${GITHUB_OWNER}:${GITHUB_PUSH_TOKEN}@github.com/${GITHUB_OWNER}/helm-repo.git
artifacts:
  files:
    - '**/*'
  name: docker-helm-values-$(date +%Y-%m-%d)
      
