version: 0.2

phases:
  install: # Install AWS cli, kubectl (needed for Helm) and Helm
    commands:
      - "API_IMAGE_TAG=$(source ./tags.txt && echo ${Api_Image_Tag})"
      - "DDB_IMAGE_TAG=$(source ./tags.txt && echo ${Dynamo_Image_Tag})"
      - "WEBAPP_IMAGE_TAG=$(source ./tags.txt && echo ${Webapp_Image_Tag})"
      - "NODEJS_IMAGE_TAG=$(source ./tags.txt && echo ${Nodejs_Image_Tag})"
      - "PYTHON_IMAGE_TAG=$(source ./tags.txt && echo ${Python_Image_Tag})"
      - "yum install -y awscli python3"
      - echo "API Ecr repo is:" $API_ECR_REPO "DDB Ecr repo is:" $DDB_ECR_REPO "NodeJs Ecr repo is:" $NODEJS_ECR_REPO "Python Ecr repo is:"  $PYTHON_ECR_REPO "Webapp Ecr repo is:" $WEBAPP_ECR_REPO "Image tag is:" $API_IMAGE_TAG
  pre_build: # Authenticate with ECR
    commands:
      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
  build: # Build Docker image, tag and push
    commands:
      - cd ${CODEBUILD_SRC_DIR}/microservices/api/ &&  docker build -t api:$API_IMAGE_TAG .
      - docker tag api:$API_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$API_ECR_REPO:$API_IMAGE_TAG
  post_build: # Push the Docker image to the ECR
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$API_ECR_REPO:$API_IMAGE_TAG
artifacts:
  files:
    - '**/*'
  name: docker-build-$(date +%Y-%m-%d)
      
